### ISSUE TITLE
Containers getting incorrectly cleaned up?

### ISSUE THREAD

**Issue by mattdodge** [meltwater/docker-cleanup#39] opened 2017-07-12 15:29 UTC
I'm a bit confused as to how `KEEP_CONTAINERS` and `KEEP_CONTAINERS_NAMED` are supposed to work together. We were running this docker container (using the [Rancher catalog stack](https://github.com/rancher/community-catalog/tree/master/templates/janitor)) with the following env vars set:
```
KEEP_CONTAINERS = "*:*"
KEEP_CONTAINERS_NAMED = "**None**"
KEEP_IMAGES = "/rancher"
```
Based on that config and the docs I would expect no containers to ever get cleaned up (each container's image should match the `KEEP_CONTAINERS` rule). However, we were seeing some start-once, data-only containers get cleaned up.

**Comment by vi7** [comment] 2017-07-27 13:41
Hi @mattdodge ! We are using pretty much the same setup and facing same kind of problems.
Specifically with Jenkins stack provided by the Rancher catalog

I've checked `checkPatterns` func in the [run.sh](https://github.com/meltwater/docker-cleanup/blob/1.8.0/run.sh#L3) and from my understanding it cannot filter out and protect containers by the `*:*` as well as the images with tag `latest` as far as image names in that case are reported without `:latest`.
`busybox` image used in the Jenkins stack from Rancher is a good example of that, you can try `docker inspect --format='{{(index .Config.Image)}}' <jenkins-datavolume-container-id>` and check the output

**Comment by jnjackins** [comment] 2017-07-28 19:43
I believe the expected behavior is that the container will be kept if at least one of the KEEP_CONTAINERS or KEEP_CONTAINERS_NAMED conditions match. So it must be the case that either a) these containers do no match either rule, or b) there is a bug. 

In your case, no containers will ever match `**None**`. What is the image name of the containers being destroyed?

**Comment by jnjackins** [comment] 2017-07-28 19:45
Have you run docker-cleanup with DEBUG enabled?

**Comment by mattdodge** [comment] 2017-07-31 18:08
I would also expect that to be an `OR` operation, that didn't seem to be the case though. Haven't run with `DEBUG` and I don't have the original container names but this is what it is named now so should be close. These are the details of the container that was incorrectly getting cleaned up.
```
Image: 123456789012.dkr.ecr.us-west-2.amazonaws.com/vault-data
Container Name: API-vault-vault-data-1
```

I've anonymized our AWS/ECR ID in the image URL but it's numbers just like that. We've since changed our config to `KEEP_CONTAINERS_NAMED = *vault*` from `**None**` and it is correctly keeping the container now. I can do some more testing later today too if needed.

**Comment by seandtaber** [comment] 2017-08-02 18:11
Hi @mattdodge thanks for that info! If you could run some more testing, possibly with DEBUG enabled that would assist us in troubleshooting this issue.

**Comment by CodingContraption** [comment] 2018-03-13 13:58
@mattdodge The details you provided basically answer your question: the image name does not match the pattern `*:*`. images that are started with an implicit `latest` tag, come back without the tag by the `docker inspect --format='{{(index .Config.Image)}}' $CONTAINER_ID` command that is used in the script.

Example:
say`docker run hello-world` starts with container id 1
and `docker run hello-world:latest` starts with container id 2

`docker inspect --format='{{(index .Config.Image)}}' 1` returns `hello-world`
`docker inspect --format='{{(index .Config.Image)}}' 2` returns `hello-world:latest`

Only `hello-world:latest` will match with the `*:*` pattern.

The solution:

Use `**All**` or `.` to match everything including implicit `latest` tagged images. (`**All**` is translated to `.`: [source](https://github.com/meltwater/docker-cleanup/blob/master/run.sh#L49-L51))

I think the readme should be updated to reflect this behaviour.

**Comment by rasjoh** [comment] 2019-06-11 08:40
Won't fix due to retiring project

**Closed as completed by rasjoh** 2019-06-11 08:40 UTC
